# Development tools - NOT used in production - DEV

services:

  mongo-express:
    image: mongo-express:latest
    container_name: readquest-mongo-express
    restart: unless-stopped
    
    ports:
      # Accessible only from localhost (security)
      - "127.0.0.1:8081:8081"
    
    environment:
      # MongoDB connection URL
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@dbmongo:27017/
      
      # Optional: Enable basic authentication
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    
    depends_on:
      - dbmongo

  storybook:
    image: node:22-alpine
    container_name: readquest-storybook
    working_dir: /app

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "6006:6006"

    environment:
      - NODE_ENV=development

    command: sh -c "npm install && npm run storybook -- -p 6006 -h 0.0.0.0"

    depends_on:
      - frontend
    